import type { AreaContent } from "./AreaLanding";
const page: AreaContent = {
  name: "Hertfordshire", slug: "sell-my-broken-jaguar-hertfordshire",
  metaTitle: "Sell My Broken Jaguar Hertfordshire | Free Collection",
  description: "Sell a broken Jaguar in Hertfordshire. Free collection from Watford, St Albans, Hemel Hempstead and Stevenage. Non-runners and MOT failures welcome.",
  heroImage: "/models/f-pace-centred.webp", heroAlt: "White Jaguar F-Pace with black wheels, viewed from the front and side",
  intro: "A Jaguar with a warning light, failed MOT or accident damage can still be sold. We buy faulty and non-running Jaguars across Hertfordshire and arrange free collection, including Watford, St Albans, Hemel Hempstead and Stevenage.",
  promise: "Tell us about the car as it stands. We assess its condition, make a no-obligation offer and, if you accept, pay by bank transfer on collection day before the Jaguar leaves.",
  coverageHeading: "Collection across Hertfordshire, with the access agreed first",
  coverageIntro: "You do not need to drive a faulty car to a branch. We are based in Medway and collect throughout Hertfordshire from homes, workplaces and garages, subject to arranging access and release of the vehicle.",
  coverage: [
    {title: "Watford, St Albans and the west", text: "Watford, Bushey, Rickmansworth, St Albans, Hemel Hempstead, Berkhamsted and Tring. If parking is shared or controlled, tell us who can open the entrance and whether loading space is available."},
    {title: "Stevenage and north Hertfordshire", text: "Stevenage, Hitchin, Letchworth Garden City, Baldock and Royston. For a car at a repairer, share the workshop's opening hours, release contact and any information about wheels, steering or removed parts."},
    {title: "Welwyn, Hatfield and the east", text: "Welwyn Garden City, Hatfield, Hertford, Ware, Hoddesdon and Bishop's Stortford. Give us the actual vehicle location and flag an underground car park, narrow driveway or car blocked in by other vehicles."}
  ],
  sections: [
    {heading: "You do not need a perfect service file to ask for an offer", paragraphs: ["A full history can help explain how a Jaguar has been maintained, but gaps in the paperwork do not stop you requesting a valuation. Tell us what records you have, how many keys are available and which faults you know about. We can discuss missing documents before you commit to a sale.", "Our assessment considers age, mileage, model, specification and condition together. This includes older Jaguars and cars that need work. You can compare an offer for the car now with the cost and time involved in repairing it or preparing it for another selling route."], links: [{label: "Selling a Jaguar without service history", href: "/blog/sell-jaguar-without-service-history"}]},
    {heading: "What to tell us when the dashboard shows a warning", paragraphs: ["The exact message is more helpful than a guess at the failed part. Say when the warning appeared, whether the engine starts and whether the car has lost power or drive. If a garage has supplied a diagnosis, share it; if the cause is unknown, simply say so.", "We buy Jaguars with engine, gearbox, electrical and charging faults. A warning message alone is not a diagnosis, and requesting a valuation does not mean you need to restart or test-drive an unsafe vehicle. You can describe the symptoms you have already seen."], bullets: ["Restricted-performance messages and recurring warning lights", "Engine failure, overheating or timing-chain problems", "Gearbox faults and vehicles stuck without drive", "MOT failures and non-starting or long-standing cars"], links: [{label: "Selling with a restricted-performance warning", href: "/blog/jaguar-restricted-performance-warning"}, {label: "MOT failure: repair or sell?", href: "/blog/jaguar-failed-mot-repair-or-sell"}]},
    {heading: "Accident damage needs a clear description", paragraphs: ["For a damaged Jaguar, include photographs of the affected areas and tell us about any damage you cannot show easily. Mention deployed airbags, damaged wheels or suspension, missing parts and whether the car can roll and steer. These details affect both valuation and collection planning.", "If an insurer is involved, establish the position before agreeing to sell. Tell us any recorded category and whether a claim is still open; do not assume all damaged vehicles have the same status. We can discuss the information needed to assess your Jaguar."], links: [{label: "Selling an accident-damaged Jaguar", href: "/blog/sell-accident-damaged-jaguar"}]},
    {heading: "From an agreed offer to an organised collection", paragraphs: ["A Jaguar outside a garage in Stevenage and one in a residents' car park in Watford may need different arrangements. Confirm access, the person meeting the collector and the car's ability to move. Resolve any garage or storage charges with the relevant business before release; our free collection does not settle those bills.", "The offer is based on the description supplied. Raise changes in condition or anything omitted before collection, and confirm the final figure before handover. Payment is by secure bank transfer, cleared before the Jaguar leaves. Keep the sale receipt and DVLA notification confirmation."], links: [{label: "Collection preparation checklist", href: "/blog/non-running-jaguar-collection-checklist"}, {label: "DVLA paperwork explained", href: "/blog/dvla-paperwork-selling-broken-car"}]}
  ],
  faqs: [
    {question: "Can you buy a Jaguar with incomplete service history?", answer: "Yes, you can request a valuation with the records you have. Describe the gaps, the condition and known faults. Available invoices or a garage report can help, but a perfect history is not required to ask for an offer."},
    {question: "Do you collect from Watford, St Albans and Stevenage?", answer: "Yes. We arrange free collection across Hertfordshire, including those towns and Hemel Hempstead, Hatfield, Hertford and Bishop's Stortford. Give us the collection postcode and details of any access restrictions."},
    {question: "Can I sell a Jaguar with a restricted-performance warning?", answer: "Yes. Tell us the exact message, symptoms and any diagnosis you already have. We assess the details rather than assuming the warning has one particular cause."},
    {question: "Will you buy a Jaguar with accident damage?", answer: "We buy damaged Jaguars. Share photographs, describe the damage and disclose any insurance category or open claim before agreeing a sale. Confirm the ownership and insurer position where relevant."},
    {question: "Do I need to transport the Jaguar to you?", answer: "No. We arrange free collection from the agreed location. Let us know whether it rolls, steers, has keys or has been partly dismantled so collection can be planned."},
    {question: "Are there fees, and when do you pay?", answer: "The valuation and collection are free, with no hidden fees. Payment is by secure bank transfer on collection day, cleared before handover. Any unrelated garage or storage charges remain separate."}
  ],
  nearby: [{label: "Essex", href: "/sell-my-broken-jaguar-essex"}, {label: "Berkshire", href: "/sell-my-broken-jaguar-berkshire"}]
};
export default page;
