import type { AreaContent } from "./AreaLanding";
const page: AreaContent = {
  name:"West Sussex",slug:"sell-my-broken-jaguar-west-sussex",
  metaTitle:"Sell My Broken Jaguar West Sussex | Free Collection",
  description:"Sell your broken or non-running Jaguar in West Sussex. Free collection from Crawley, Horsham, Worthing and Chichester, with bank-transfer payment on collection.",
  heroImage:"/about/jag-f-pace-centred.webp",heroAlt:"White Jaguar F-Pace viewed from the front and side",
  intro:"A Jaguar that will not start, has failed its MOT or needs an expensive repair can still be worth selling. We buy broken, damaged and non-running Jaguars across West Sussex, with free collection from where the car is kept.",
  promise:"Get a no-obligation offer for its current condition. If you accept, we arrange collection and pay by secure bank transfer, cleared before the Jaguar leaves.",
  coverageHeading:"Collection from Crawley to the West Sussex coast",
  coverageIntro:"Whether the car is on a drive in Horsham, outside a workshop in Chichester or parked near your home in Worthing, start with its postcode and condition. We are based in Medway and collect across West Sussex; you do not need to bring the Jaguar to us.",
  coverage:[
    {title:"Crawley and Mid Sussex",text:"Crawley, East Grinstead, Haywards Heath and Burgess Hill. If the Jaguar is at a garage, give us its opening hours and confirm that it can be released before agreeing collection."},
    {title:"Horsham and inland towns",text:"Horsham, Billingshurst, Pulborough, Midhurst and Petworth. For a long driveway, narrow entrance or shared access, photographs help us plan how to reach and load the car."},
    {title:"Worthing and the coast",text:"Worthing, Shoreham-by-Sea, Littlehampton, Bognor Regis and Chichester. Tell us about parking restrictions, a basement car park or limited loading space before we book the visit."}
  ],
  sections:[
    {heading:"Selling a faulty Jaguar without paying for another repair",paragraphs:["You may have a written quote for a gearbox repair, a recurring warning light or an engine that has stopped altogether. You do not need to authorise work just to request a valuation. Tell us what is happening and include any diagnosis you already have.","We assess the model, year, mileage, specification, condition and reported fault together. A repair estimate is useful context, but it does not by itself tell you what someone will pay for the complete car. Compare an actual offer with the cost of the work and your plans for the Jaguar."],bullets:["Engine failure, timing-chain problems or overheating","Gearbox faults, loss of drive and non-starters","Electrical faults and I-Pace charging problems","MOT failures, accident damage and long-standing cars"],links:[{label:"What affects a non-runner's value?",href:"/blog/non-runner-jaguar-value"},{label:"Repair or sell after an MOT failure",href:"/blog/jaguar-failed-mot-repair-or-sell"}]},
    {heading:"Before you accept a scrap-car quote in West Sussex",paragraphs:["If you searched for a scrap Jaguar buyer because the car no longer drives, get a valuation for it in its current condition first. We buy Jaguars with faults; being a non-runner does not automatically mean the only option is disposal.","Compare the amount you will actually receive, whether collection is included and what happens if the condition differs from the description. Our valuation is free, collection is free and there are no hidden fees. Describe known faults, damage, missing keys or removed parts so the offer is based on the right information."],links:[{label:"Get a more accurate Jaguar valuation",href:"/blog/accurate-online-valuation-broken-jaguar"}]},
    {heading:"When the car cannot roll, steer or leave the garage",paragraphs:["A car that starts but cannot select a gear needs different collection planning from one with a flat tyre or a locked steering wheel. Tell us what you know without trying to force controls or move an unsafe car. Include whether the wheels turn, whether keys are available and any advice the garage has given.","For workshop collection, settle release arrangements directly with the garage and tell us about access times. If the car has been left on private land, make sure the person controlling that land agrees to collection. We confirm the practical details before the vehicle is moved."],links:[{label:"Prepare for non-runner collection",href:"/blog/non-running-jaguar-collection-checklist"}]},
    {heading:"Logbook, service history and a private registration",paragraphs:["Have the V5C, keys and available service records ready. If the logbook or service history is missing, say so when you request the offer; we can discuss what is needed for your sale. A missing MOT is not an obstacle to asking for a valuation because collection can be arranged without driving the car to us. If a finance agreement or insurance claim is still open, raise it before agreeing a sale.","Tell us before handover if you want to keep a private registration. Complete the applicable DVLA process before selling, especially if the Jaguar cannot move under its own power. Keep the sale receipt and confirmation that DVLA has been notified."],links:[{label:"DVLA paperwork when selling",href:"/blog/dvla-paperwork-selling-broken-car"},{label:"Keeping your private number plate",href:"/blog/keep-private-number-plate-selling-broken-jaguar"}]}
  ],
  faqs:[
    {question:"Do you collect non-running Jaguars throughout West Sussex?",answer:"Yes. We arrange free collection across West Sussex, including Crawley, Horsham, Worthing and Chichester. Give us the postcode and explain any access or loading restrictions so the collection can be planned."},
    {question:"Do I have to get the fault diagnosed first?",answer:"No. Describe the symptoms and share a report if you already have one. If the cause is unknown, say that. You do not need to pay for repairs or diagnosis just to request a valuation."},
    {question:"Can you collect my Jaguar from a West Sussex garage?",answer:"Yes, subject to the garage's release and access arrangements. Tell us the address, opening hours and whether the car rolls and steers. Resolve any outstanding garage charges directly before handover."},
    {question:"How quickly can you collect, and when will I be paid?",answer:"Collection is usually arranged within 24 to 48 hours of accepting an offer, subject to scheduling and access. Confirm the appointment with us. Payment is by secure bank transfer on collection day, cleared before the car leaves."},
    {question:"Can the valuation change when you see the car?",answer:"The offer is based on the information supplied. Previously undisclosed damage, faults or missing parts may affect it. Describe the Jaguar fully and confirm the agreed figure before handover; collection is free and there are no hidden fees."},
    {question:"Can I sell an MOT failure or a Jaguar on SORN?",answer:"Yes. Tell us its status when requesting an offer. A non-running car can be collected without you driving it to us. Keep it lawfully stored until collection and follow the correct DVLA sale-notification process."}
  ],
  nearby:[{label:"East Sussex",href:"/sell-my-broken-jaguar-east-sussex"},{label:"Surrey",href:"/sell-my-broken-jaguar-surrey"},{label:"Kent",href:"/sell-my-broken-jaguar-kent"}]
};
export default page;
