import type { AreaContent } from "./AreaLanding";
const page: AreaContent = {
  name: "Suffolk", slug: "sell-my-broken-jaguar-suffolk",
  metaTitle: "Sell My Broken Jaguar Suffolk | Free Collection",
  description: "Sell your broken Jaguar in Suffolk with free collection. Non-runners, MOT failures and damaged cars bought in Ipswich, Bury St Edmunds, Lowestoft and beyond.",
  heroImage: "/models/xj.webp", heroAlt: "White Jaguar XJ saloon on a road beside trees",
  intro: "A broken Jaguar taking up space on the drive? We buy faulty, damaged and non-running Jaguars across Suffolk, including Ipswich, Bury St Edmunds and Lowestoft. Get a free valuation with collection included.",
  promise: "Tell us about the car as it stands, even if it has been off the road for a while. There is no need to buy another vehicle from us, and payment clears by bank transfer before your Jaguar leaves.",
  coverageHeading: "Free collection across Suffolk",
  coverageIntro: "Our team is based in Medway and collects Jaguars across Suffolk. You do not need to bring the car to a buying branch. We agree a collection slot after checking the postcode, vehicle condition and access.",
  coverage: [
    {title: "Ipswich, Felixstowe and Woodbridge", text: "We cover Ipswich, Felixstowe, Woodbridge and surrounding villages. Tell us if your Jaguar is in a shared parking area, behind a gate or at a garage, so we can agree access with the person responsible."},
    {title: "Bury St Edmunds and west Suffolk", text: "Collection covers Bury St Edmunds, Newmarket, Haverhill, Sudbury and nearby areas. For a car kept in a barn, yard or workshop, share the entrance details and whether it can roll and steer."},
    {title: "Stowmarket, Lowestoft and the coast", text: "Stowmarket, Framlingham, Beccles, Lowestoft, Saxmundham and Aldeburgh are covered. At a rural property, the full address and a photograph of the approach help us plan the collection."}
  ],
  sections: [
    {heading: "Selling a Jaguar that has been standing unused", paragraphs: ["A car left waiting for a repair can become another job you keep putting off. You can ask us for a valuation without first getting it running, booking an MOT or committing to a repair bill. Tell us when it was last used and why it was parked up; if you do not know the cause of a fault, say so.", "Describe its condition today, rather than how it drove before it was stored. Clear photographs and any existing garage findings help us assess it. You do not need to attempt a jump-start or move the car simply to make an enquiry."], bullets: ["When did it last run, and what happened before it stopped?", "Are the keys available, and are any parts missing?", "Are any tyres flat, wheels locked or warning messages showing?", "Where is it parked, and can a collection vehicle reach it?"], links: [{label: "What affects a non-running Jaguar's value?", href: "/blog/non-runner-jaguar-value"}, {label: "Selling a Jaguar without service history", href: "/blog/sell-jaguar-without-service-history"}]},
    {heading: "Compare your options before choosing a scrap quote", paragraphs: ["An MOT failure or engine problem does not, by itself, tell you what your Jaguar is worth. Its model, age, mileage, specification and remaining condition all matter. A specialist offer gives you another figure to compare with a repair estimate or scrap quotation.", "Compare the amount you will receive after any fees, whether collection is included and what condition the quote assumes. Our collection is free, and you can decline our offer. Describe faults and damage accurately: the valuation relies on those details and may change if the vehicle differs from the description."], links: [{label: "Failed MOT: repair your Jaguar or sell it?", href: "/blog/jaguar-failed-mot-repair-or-sell"}]},
    {heading: "Faulty Jaguars bought without a part exchange", paragraphs: ["You can sell to us without buying a replacement car. We consider Jaguars with engine, gearbox, electrical and cooling problems, accident damage or a failed MOT, including the XF, XE, XJ, F-Pace, E-Pace and I-Pace. Older models and cars that no longer start are welcome too.", "For a dashboard warning, send the exact wording and explain what the car does. A warning message is not a diagnosis, so share a repairer's findings if you have them and distinguish confirmed faults from suspected ones. This helps us assess the Jaguar without asking you to promise that a particular repair will fix it."], links: [{label: "Jaguar restricted-performance warnings", href: "/blog/jaguar-restricted-performance-warning"}, {label: "Cooling problems: weighing up repair and sale", href: "/blog/jaguar-coolant-loss-overheating-repair-or-sell"}]},
    {heading: "Plan the collection before the day arrives", paragraphs: ["If the Jaguar is at a garage, storage yard or another person's property, agree its release and arrange for someone with authority to hand it over. Settle any separate repair or storage charges with that business. Tell us about narrow entrances, soft ground, height restrictions or a car that cannot be put into neutral before we book the collection.", "Have the keys and available vehicle documents together, and tell us early about missing paperwork, outstanding finance, an insurance claim or a private plate. On collection day, confirm the agreed amount and check that the bank transfer has cleared before the car leaves. Keep the sale receipt and DVLA confirmation for your records."], links: [{label: "Non-running Jaguar collection checklist", href: "/blog/non-running-jaguar-collection-checklist"}, {label: "Sale paperwork explained", href: "/blog/dvla-paperwork-selling-broken-car"}]}
  ],
  faqs: [
    {question: "Will you buy a Jaguar that has been off the road for months?", answer: "Yes. Tell us when it last ran, why it was taken off the road and what condition it is in now. You can request an offer without repairing or starting it first. We will confirm the collection arrangements if you accept."},
    {question: "Do you collect in Ipswich, Bury St Edmunds and Lowestoft?", answer: "Yes. Free collection covers those towns and the wider Suffolk area, including Felixstowe, Woodbridge, Sudbury and Stowmarket. Send the full postcode and access details so we can agree a collection slot."},
    {question: "Can you collect from a village property or storage yard?", answer: "We arrange collection from the agreed location after checking access. Tell us about gates, narrow tracks, soft ground and whether the Jaguar can roll and steer. A yard or garage must agree to release the car, and its separate charges remain your responsibility."},
    {question: "Should I get an MOT or repair quote before asking for a valuation?", answer: "Neither is needed to request an offer. Describe the faults you know about and send any reports you already have. An existing repair estimate can help you compare your options, but you do not need to commission one just to contact us."},
    {question: "Do I have to buy another car from you?", answer: "No. This is a sale of your Jaguar, with no replacement purchase required. The valuation is free and carries no obligation to accept."},
    {question: "How and when will I be paid?", answer: "Payment is by secure bank transfer on collection day, cleared before your Jaguar leaves. Confirm the agreed amount before handover and keep the sale receipt and DVLA confirmation."}
  ],
  nearby: [{label: "Essex", href: "/sell-my-broken-jaguar-essex"}, {label: "Hertfordshire", href: "/sell-my-broken-jaguar-hertfordshire"}]
};
export default page;
