import type { AreaContent } from "./AreaLanding";
const page: AreaContent = {
  name: "Berkshire", slug: "sell-my-broken-jaguar-berkshire",
  metaTitle: "Sell My Broken Jaguar Berkshire | Free Collection",
  description: "Sell your faulty or non-running Jaguar in Berkshire. Free collection in Reading, Slough, Newbury and Bracknell. Get a no-obligation valuation today.",
  heroImage: "/models/xe.webp", heroAlt: "Red Jaguar XE saloon on a winding road",
  intro: "Has a fault put your plans to sell your Jaguar on hold? We buy broken, damaged and non-running Jaguars across Berkshire, with free collection from Reading, Slough, Newbury and the surrounding towns.",
  promise: "You can sell the car in its current condition without bringing it to a showroom. Request a free valuation, agree collection if you accept, and receive cleared bank-transfer payment before handover.",
  coverageHeading: "We collect from where your Jaguar is kept in Berkshire",
  coverageIntro: "A car at a Reading workshop needs a different collection arrangement from one on a rural drive near Newbury. Give us the full collection postcode and the practical details. We collect from our Medway base, so this is a collection service rather than a Berkshire drop-off branch.",
  coverage: [
    {title: "Reading, Wokingham and Bracknell", text: "We cover Reading, Caversham, Tilehurst, Wokingham and Bracknell. For a workplace or shared car park, arrange permission and tell us about security gates, entry times or height limits."},
    {title: "Slough, Windsor and Maidenhead", text: "Collections include Slough, Windsor, Maidenhead and Ascot. Let us know if the car is in a residents' bay, underground parking or another location with limited loading space."},
    {title: "Newbury and West Berkshire", text: "We collect around Newbury, Thatcham and Hungerford. A postcode plus directions to the actual vehicle helps with a property reached by a private lane or a separate workshop entrance."}
  ],
  sections: [
    {heading: "Three figures to keep separate when selling a faulty Jaguar", paragraphs: ["A dealer's asking price for a roadworthy Jaguar is not an offer for yours. A repair quote is a cost estimate, not a valuation. The useful third figure is what a buyer will pay for your car with the fault disclosed.", "Ask for an offer using the Jaguar's registration, mileage, specification and actual condition. You can then compare selling now with the cost, time and uncertainty of a repair. Include any written diagnosis you already have; a valuation request does not require you to authorise more work."], links: [{label: "What affects a broken Jaguar's value?", href: "/blog/non-runner-jaguar-value"}, {label: "Details that make an online valuation more accurate", href: "/blog/accurate-online-valuation-broken-jaguar"}]},
    {heading: "Selling without a dealer visit or a replacement-car purchase", paragraphs: ["If the Jaguar cannot be driven, travelling to a buying appointment can become another job to organise. We arrange collection from its location after agreeing the offer and access. There is no requirement to buy another car from us.", "We consider the whole Jaguar, including its model, age, mileage, bodywork, interior, history and faults. An older XJ, a high-mileage XF or an XE with a gearbox problem can still be submitted for a valuation. Be clear about missing parts or work already started, as these affect the assessment."], bullets: ["Non-starting engines and cars with no drive", "Gearbox warnings or restricted performance", "MOT failures and damaged bodywork", "Electrical and I-Pace charging problems"], links: [{label: "Selling with a gearbox fault", href: "/blog/jaguar-gearbox-fault-repair-or-sell"}]},
    {heading: "Collection details that prevent a wasted visit", paragraphs: ["Use the postcode where the vehicle is parked, even if you live elsewhere. RG and SL postcodes extend beyond individual town boundaries, so the exact address is more useful than a broad area label. Tell us whether keys are available, whether the wheels turn and whether the steering can be moved.", "If a garage holds the car, confirm that it can be released and settle any charges directly with them. If you will be at work on the collection day, discuss who will be present and authorised to complete handover before the appointment. We confirm the arrangements with you; do not assume a third party can release the vehicle."], links: [{label: "Non-runner collection checklist", href: "/blog/non-running-jaguar-collection-checklist"}]},
    {heading: "Check the offer, payment and paperwork together", paragraphs: ["Our valuation is free and collection has no hidden fees. The offer depends on the information you provide, so include all known faults and damage. If something material has not been disclosed, discuss the revised position before handover rather than relying on the original estimate.", "Payment is by secure bank transfer on collection day and must clear before the car leaves. Have your available logbook, keys and service records ready. Tell us about missing paperwork, finance or an unresolved insurance claim before agreeing a sale, and deal with a private plate you want to keep before transferring the vehicle."], links: [{label: "What if service history is missing?", href: "/blog/sell-jaguar-without-service-history"}, {label: "Keeping a private registration", href: "/blog/keep-private-number-plate-selling-broken-jaguar"}]}
  ],
  faqs: [
    {question: "Do you collect broken Jaguars across Berkshire?", answer: "Yes. Free collection covers Reading, Slough, Windsor, Maidenhead, Bracknell, Wokingham, Newbury and surrounding Berkshire locations. Provide the exact postcode and access details when requesting your offer."},
    {question: "Can I sell a Jaguar that has already been partly dismantled?", answer: "Tell us exactly what has been removed, where the parts are and whether the vehicle rolls and steers. We can discuss the car and collection requirements before making an offer; do not describe it as complete if parts are missing."},
    {question: "Is a scrap quote the only option for a non-running Jaguar?", answer: "No. You can request an offer for the Jaguar in its current condition and compare it with other available options. The model, mileage, specification and remaining condition matter alongside the fault."},
    {question: "Can you collect while my Jaguar is at a Reading garage?", answer: "Yes, provided release and access are agreed with the garage. Let us know its address, opening hours, any removed parts and whether the vehicle can be loaded. Garage charges remain separate from our collection service."},
    {question: "Is the valuation instant and guaranteed?", answer: "We assess the details you supply and come back with an offer. The figure is based on that description, so previously undisclosed faults, damage or missing items may affect it. Confirm the agreed amount before handover."},
    {question: "When will I receive the money?", answer: "Payment is by secure bank transfer on collection day, cleared before the Jaguar leaves. There is no obligation to accept the valuation and no need to purchase another vehicle."}
  ],
  nearby: [{label: "Hampshire", href: "/sell-my-broken-jaguar-hampshire"}, {label: "Surrey", href: "/sell-my-broken-jaguar-surrey"}]
};
export default page;
