import type { AreaContent } from "./AreaLanding";
const page: AreaContent = {
  name: "Buckinghamshire", slug: "sell-my-broken-jaguar-buckinghamshire",
  metaTitle: "Sell My Broken Jaguar Buckinghamshire | Free Collection",
  description: "Sell your broken Jaguar in Buckinghamshire. Free collection in High Wycombe, Aylesbury and Milton Keynes. Non-runners, engine faults and MOT failures bought.",
  heroImage: "/models/e-pace.webp", heroAlt: "White Jaguar E-Pace on a road, viewed from the front and side",
  intro: "Your Jaguar does not have to be a good runner to get an offer. We buy broken and non-running Jaguars across Buckinghamshire, with free collection in High Wycombe, Aylesbury, Milton Keynes and surrounding areas.",
  promise: "Describe the fault and where the car is kept. We value it in its current condition, arrange collection if you accept and pay by secure bank transfer before it leaves.",
  coverageHeading: "Collection in Buckinghamshire and Milton Keynes",
  coverageIntro: "We collect from our Medway base, so you do not need to transport the Jaguar to us. Give us the full postcode and explain how the vehicle can be reached; we agree the loading arrangements before booking collection.",
  coverage: [
    {title: "High Wycombe and south Bucks", text: "High Wycombe, Marlow, Beaconsfield, Gerrards Cross and Burnham. For a sloping drive or tight parking space, send a photograph of the approach and tell us if the car is blocked in."},
    {title: "Aylesbury and the Chiltern towns", text: "Aylesbury, Princes Risborough, Wendover, Amersham and Chesham. If the Jaguar is at a village property or workshop, include entrance directions and any restrictions on when it can be released."},
    {title: "Buckingham and Milton Keynes", text: "Buckingham, Winslow, Milton Keynes, Bletchley and Newport Pagnell are covered. In a managed or workplace car park, confirm gate access, height limits and a suitable place for collection."}
  ],
  sections: [
    {heading: "A non-runner needs a buyer who understands the condition", paragraphs: ["Some selling routes are designed around an inspection and a test drive of a running car. If your Jaguar will not start or has lost drive, say so at the beginning. Our service is for broken and damaged Jaguars as well as cars with less serious faults, and free collection forms part of the sale.", "You do not need to repair the car to request an offer. We consider its model, year, mileage, specification and overall condition alongside the problem. Share a garage report if you have one, but an unknown cause is something you can explain rather than pay to diagnose before contacting us."], links: [{label: "How a non-running Jaguar is valued", href: "/blog/non-runner-jaguar-value"}]},
    {heading: "Starts, rolls and steers: three separate collection questions", paragraphs: ["An engine that runs does not mean the Jaguar can be loaded easily. It may be stuck in gear, have a locked wheel or be parked where a collection vehicle cannot get close. Equally, a car that will not start may still roll and steer normally.", "Tell us what you already know about the car and its position. Do not force the gear selector, release controls or move a vehicle if you are unsure it is safe. We will discuss the details needed to arrange collection."], bullets: ["Does the engine start, and when was it last used?", "Can the car roll and steer, as far as you know?", "Are the keys available, and are any parts missing?", "Is there space to approach, load and leave?"], links: [{label: "Prepare your Jaguar for collection", href: "/blog/non-running-jaguar-collection-checklist"}]},
    {heading: "Compare a repair decision with an offer for the car now", paragraphs: ["A timing-chain concern, a gearbox repair or repeated warning lights can leave you unsure whether to spend more. Get the fault and proposed work explained by your repairer, then compare the full quoted cost with an offer for the Jaguar in its present condition. Avoid basing the decision only on advertised prices for healthy cars.", "We buy models including the XF, XE, XJ, F-Pace, E-Pace and I-Pace with faults or damage. Tell us about recent work as well as unresolved problems; a new part does not automatically mean the original fault is fixed. A free valuation gives you an option without committing you to sell."], links: [{label: "F-Pace timing-chain problems: repair or sell?", href: "/blog/jaguar-f-pace-timing-chain-repair-or-sell"}, {label: "Jaguar gearbox faults and selling options", href: "/blog/jaguar-gearbox-fault-repair-or-sell"}]},
    {heading: "Agree the handover before clearing your diary", paragraphs: ["Once you accept, confirm the collection day, vehicle location and person meeting the collector. If a garage or storage business holds the car, agree its release and settle any charges directly. Our collection is free; it does not include unrelated workshop or storage bills.", "Keep the description up to date if the car's condition changes or parts are removed. The offer relies on the information provided, and undisclosed faults or damage may affect it. Confirm the agreed amount, check the bank transfer has cleared and retain your sale receipt and DVLA confirmation. Raise missing documents, finance, insurance issues or a private plate before the sale is agreed."], links: [{label: "Paperwork when selling a broken Jaguar", href: "/blog/dvla-paperwork-selling-broken-car"}]}
  ],
  faqs: [
    {question: "Will you buy my Jaguar if it cannot be test-driven?", answer: "Yes. We buy non-running Jaguars and cars with faults that prevent a test drive. Describe the condition and any diagnosis you have so we can assess the car and arrange suitable collection."},
    {question: "Does your Buckinghamshire service include Milton Keynes?", answer: "Yes. We cover Milton Keynes and nearby places such as Bletchley and Newport Pagnell, as well as High Wycombe, Aylesbury, Buckingham and the Chiltern towns."},
    {question: "Can you collect from a steep drive or a narrow entrance?", answer: "Tell us about the access before agreeing collection. Photographs, the entrance width and whether the car can move help us assess the arrangements. We confirm access and loading details rather than assuming every location is straightforward."},
    {question: "Do you buy F-Pace and E-Pace models with engine problems?", answer: "Yes. Send the registration, mileage, symptoms and any garage findings. You can request a valuation without carrying out repairs first, and we also buy other Jaguar models with engine or gearbox faults."},
    {question: "Is collection free if the car is at a garage?", answer: "Our collection is free from the agreed location, including a garage that has agreed to release the vehicle. Any outstanding garage charges must be resolved separately before handover."},
    {question: "When do I receive payment for my Jaguar?", answer: "Payment is by secure bank transfer on collection day, cleared before the car leaves. Confirm the agreed price and payment before completing the handover; the valuation carries no obligation to sell."}
  ],
  nearby: [{label: "Hertfordshire", href: "/sell-my-broken-jaguar-hertfordshire"}, {label: "Berkshire", href: "/sell-my-broken-jaguar-berkshire"}]
};
export default page;
