import type { AreaContent } from "./AreaLanding";
const page: AreaContent = {
  name: "Hampshire", slug: "sell-my-broken-jaguar-hampshire",
  metaTitle: "Sell My Broken Jaguar Hampshire | Free Collection",
  description: "Sell a broken Jaguar in Hampshire with free collection. Non-runners and MOT failures bought in Southampton, Portsmouth, Winchester and Basingstoke.",
  heroImage: "/models/xf.webp", heroAlt: "Blue Jaguar XF saloon viewed from the front and side",
  intro: "An engine fault or failed MOT does not have to mean another repair bill. We buy broken and non-running Jaguars across Hampshire, including Southampton and Portsmouth, and collect the car free of charge.",
  promise: "Get an offer based on your Jaguar's condition, then choose whether to sell. Payment is by secure bank transfer on collection day, cleared before handover.",
  coverageHeading: "Hampshire collection, from the cities to the New Forest",
  coverageIntro: "We are based in Medway and arrange collection across mainland Hampshire. Give us the car's actual location, which may be different from your home address. There is no need to get a non-runner to a buying centre.",
  coverage: [
    {title: "Southampton, Portsmouth and the Solent", text: "We collect in Southampton, Portsmouth, Eastleigh, Fareham, Gosport and Havant. For a car in a managed parking area, let us know the entry arrangements, height restrictions and who can authorise access."},
    {title: "Winchester and north Hampshire", text: "Winchester, Basingstoke, Andover, Fleet, Farnborough and Aldershot are covered. If the Jaguar is awaiting a decision at a workshop, confirm its release arrangements and tell us when staff will be available."},
    {title: "New Forest and surrounding towns", text: "Collections include Romsey, Ringwood, Lymington, Alton and Petersfield. Describe any narrow approach, gravel driveway or restricted turning space so we can plan loading before setting a date."}
  ],
  sections: [
    {heading: "Get a Jaguar valuation before deciding to scrap it", paragraphs: ["A non-running XF or F-Pace is still a complete vehicle with its own specification, history and condition. We consider those details alongside the fault when making an offer. You can ask for that figure before choosing a repair, a private sale or a scrap-car service.", "Compare offers on the same description of the car and check the amount left after collection or administration charges. Our valuation and collection are free, with no hidden fees. You can assess the offer without any obligation to sell."], links: [{label: "How non-running Jaguars are valued", href: "/blog/non-runner-jaguar-value"}]},
    {heading: "A warning light, no drive or a repair quote you cannot justify", paragraphs: ["You do not need a perfect diagnosis to start. Tell us what happened, whether the engine starts and whether the car can move. A garage report or repair estimate can help if you already have one, but you do not need to pay for new work just to request a valuation.", "Include faults that appear intermittently, not just the reason the car is parked. Accurate details help us assess the Jaguar before collection and reduce the chance of a different condition being discovered at handover."], bullets: ["Engine failure, overheating and timing-chain faults", "Automatic gearbox problems and loss of drive", "Electrical warnings and I-Pace charging faults", "MOT failures, body damage and high-mileage cars"], links: [{label: "Common Jaguar faults when selling", href: "/blog/common-jaguar-faults"}, {label: "Repair or sell an MOT failure?", href: "/blog/jaguar-failed-mot-repair-or-sell"}]},
    {heading: "A Jaguar at a garage or behind a parking barrier", paragraphs: ["For workshop collection in Southampton, Portsmouth or elsewhere in Hampshire, agree release with the garage first. Tell us about opening hours, any parts removed during diagnosis and whether the vehicle can roll and steer. Any garage bill or storage charge is separate from our free collection service.", "At a flat, workplace or managed car park, check who can provide access. We need to know about barriers, height limits and room to load. Send the exact location and photographs if access is unclear; do not move an unsafe car simply to make collection easier."], links: [{label: "What to check before non-runner collection", href: "/blog/non-running-jaguar-collection-checklist"}]},
    {heading: "Know what happens before the Jaguar leaves", paragraphs: ["If you accept the offer, we agree the collection details with you. Timing depends on availability and access, so confirm the appointment before making plans around it. The vehicle description is checked, and any undisclosed damage or missing items may affect the offer. Confirm the final figure before handover.", "Have your keys, available V5C and service records ready. Flag missing documents, outstanding finance or an open insurance claim early. If you want to retain a private registration, complete the relevant process before selling. Check the bank transfer has cleared and keep the sale and DVLA records."], links: [{label: "Selling paperwork and DVLA notification", href: "/blog/dvla-paperwork-selling-broken-car"}]}
  ],
  faqs: [
    {question: "Can you collect a Jaguar that will not start in Hampshire?", answer: "Yes. We arrange free collection for non-running Jaguars across mainland Hampshire. Tell us if the wheels or steering are locked, the keys are missing or access is restricted so suitable arrangements can be confirmed."},
    {question: "Are Southampton and Portsmouth included?", answer: "Yes. Both cities are included, along with places such as Winchester, Basingstoke, Fareham and Eastleigh. Start with the postcode where the car is actually kept."},
    {question: "Must I repair the Jaguar or renew its MOT first?", answer: "No. You can request an offer for the car in its current condition. Describe the faults and MOT result honestly; you do not need to drive it to us."},
    {question: "Does free collection cover an outstanding garage bill?", answer: "No. Our collection is free, but any repair, diagnosis or storage charges agreed with a garage remain separate. Resolve release arrangements with the garage before we collect."},
    {question: "When do you pay for the car?", answer: "We pay by secure bank transfer on collection day, cleared before the Jaguar leaves. Confirm the agreed amount and check payment before completing handover."},
    {question: "Do you cover the Isle of Wight from this Hampshire service?", answer: "This page covers mainland Hampshire. If the car is on the Isle of Wight, call us to discuss the location before relying on a collection arrangement."}
  ],
  nearby: [{label: "West Sussex", href: "/sell-my-broken-jaguar-west-sussex"}, {label: "Surrey", href: "/sell-my-broken-jaguar-surrey"}]
};
export default page;
